### ISSUE TITLE
running isnobal less than 1001 time steps searches for filenames with less than 4 digit numbers

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#11]
In gitlab by @pkormos on May 24, 2017, 14:17

all input files are named with 4 digit numbers, for example in.0001. If I only want to run isnobal for 700 timesteps, it looks for in.001 or if i only want to run it for 48 timesteps, it looks for in.01. I think we need to either make is standard to name files with 4 digits, or make it robust enough to look for in.0001, and if that's no there look for in.001, and if that's not there look for in.01.  That's just an idea, though.

Love, Patrick

**Comment by scotthavens** [comment]
In gitlab by @micahsandusky on May 30, 2017, 16:15

assigned to @micahsandusky

**Comment by scotthavens** [comment]
In gitlab by @micahsandusky on May 30, 2017, 16:18

I am working on a fix that will look for the files matching the given prefix and calculate the suffix length. Basically, all the files will need to have a consistent time-step length in the directory.

**Comment by micahjohnson150** [comment]
Not related to smrf. should be moved to either AWSF or IPW
