### ISSUE TITLE
test_variables in test_full_smrf.py doesn't assert anything 

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/smrf#128]
[Line 44](https://github.com/USDA-ARS-NWRC/smrf/blob/e4d0f67ba2bdf32c44d383b6ffe10657020d497d/tests/test_full_smrf.py#L44) doesnt't assert anything. And then in [Line 81](https://github.com/USDA-ARS-NWRC/smrf/blob/e4d0f67ba2bdf32c44d383b6ffe10657020d497d/tests/test_full_smrf.py#L81) also doesn't assert anything so the test is always successful. GULP.

**Comment by scotthavens** [comment]
Tested with fresh clone and this does not pass.

**Comment by micahjohnson150** [comment]
@scotthavens I wiped mine clean, clones master, checkedout develop add the assertion statement and still passed locally. I made a new branch called test_issues_#128 and pushed to the repo. It also passed on TravisCI. Take a look at that branch and lets see if there is something I am missing that you have.

**Comment by micahjohnson150** [comment]
Can you check out your branch and push to see if travisCI passes/fails it too?

**Comment by scotthavens** [comment]
This was an IPW build problem on my part. Rebuilt IPW and the tests pass.

**Comment by scotthavens** [comment]
@micahjohnson150 was this merged as well?
