### ISSUE TITLE
Gold config update

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#142]
The gold config was not updated in the config file overhaul PR #126. Update the gold config file and make a script that allows for recreation of the gold files.

**Comment by micahjohnson150** [comment]
Just a note like I sent in the email about the change in defaults. If the goal is only change the files that need to be changed as a result of #123 then be sure to change the defaults back for wind reduction 1.0 to 0.7 and new_snow_density from susong1999 to Marks2017 after the config file changelog is applied.
