### ISSUE TITLE
update weather_forecast_retrieval

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#146]
`weather_forecast_retrieval` is now a pip install. This would help with the requirements and docker build.

The gold files will have to be updated as there is a small known change when going from `pygrib` to `xarray`, see the [wontfix issue](https://github.com/USDA-ARS-NWRC/weather_forecast_retrieval/issues/9). Will need to document the changes but aren't quite using the `opendap` HRRR files yet.

**Comment by jomey** [comment]
Can I sneak this in with my latest work on #145?
One of my failing specs for Travis is it not pulling the latest WFR and complaining about a time zone issue there. It passes on my local with the latest WFR installed.

**Comment by scotthavens** [comment]
I see your build error which is with HRRR timezones. It might be a little stretch but the changes you are making are affecting the HRRR loading so it's a bit of scope creep. You could tackle this first then see if it fixes the build? I'd like to limit scope creep on issues and PR's but it does happen!
