### ISSUE TITLE
Test warning for logger

### ISSUE THREAD

**Issue by jomey** [USDA-ARS-NWRC/smrf#174]
Still getting a warning on my local:

```
test_timezone_error (smrf.tests.test_model_framework.TestModelFrameworkMST) ... /Volumes/warehouse/projects/miniconda/envs/isnoda/lib/python3.7/traceback.py:220: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Volumes/warehouse/projects/ARS/smrf/smrf/tests/RME/output/log.txt' mode='a' encoding='UTF-8'>
  tb.tb_frame.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by scotthavens** [comment]
This is related to the root logger handlers not being cleaned up between tests. I'm still unclear as to why this became a problem recently and hasn't been a problem before. I think the solution for the tests is to make sure that the root logger is cleared before each of the individual tests in the `setup` method.

[Cleaning up the root handlers](https://github.com/USDA-ARS-NWRC/smrf/blob/d6f062a5487bd4e6da1c3f78ec6269c4b1f135a9/smrf/framework/model_framework.py#L142)

**Comment by jomey** [comment]
I think your idea of a more centralized logger handling in SMRF could address this as well. Currently it feels very 'manual' to get this to work in various places throughout the package.

**Comment by scotthavens** [comment]
SMRF was our first logging implementation so it's fairly ad hoc. A possible route is a logger class in `model_framework` that could be imported into any other class to handle the logging for a particular module
