### ISSUE TITLE
Scipy and Python 3.9

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#207]
Looks like Scipy v1.4.1 doesn't support Python 3.9. Consider updating the requirements for scipy to install with newer Python versions. This has become apparent in the unittests for 3.9.

**Comment by jomey** [comment]
FYI, all my recent PR were tested with scipy version 1.5.2 installed and no issues.

**Comment by scotthavens** [comment]
Looks like 1.5.X and 1.6.X also work based on the GH actions. At the moment, scipy was fixed to <1.5.0
