### ISSUE TITLE
Albedo decay function

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#21]
In gitlab by @micahsandusky on Jul 18, 2017, 09:24

We need a way to include litter effects to decay the albedo and increase melt in the later season. This will help with melt in big snow years like this one.

**Comment by scotthavens** [comment]
In gitlab by @micahsandusky on Jul 21, 2017, 12:17

mentioned in commit 13ca409f8bb4aabfc636ff8e28bc924f83df6a16

**Comment by micahjohnson150** [comment]
Added in and functioning. Needs some enhancement and thorough testing.
