### ISSUE TITLE
storms function in storms.py

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/smrf#35]
if storms function in storms.py is not used it should be deleted.

**Comment by scotthavens** [comment]
There are 2 duplicate functions in `precip.storms` and `storms.storms`, looking into which one is actually used.

**Comment by scotthavens** [comment]
`storms.storms` is the exact same as `storms.time_since_storm` and `precip.storms` is not used anywhere.

**Comment by scotthavens** [comment]
And `precip.storms_time` was also a duplicate...
