### ISSUE TITLE
Documentation for contributing

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#49]
The link in the repository CONTRIBUTING.rst points to a page that does not exist.

**Comment by scotthavens** [comment]
Also, the credits are not properly linked. Can we link the authors github username to that list?

**Comment by micahjohnson150** [comment]
Ok I will put this on the to-do for the next version. The user names is a great idea.

**Comment by micah-prime** [comment]
I'm working on updating some of the info in the docs/CONTRIBUTING.rst. I know HISTORY, AUTHORS, and CONTRIBUTING have been moved into docs, so can the original versions of these files that are not in docs/ be removed from the repository?
