### ISSUE TITLE
When stations are None

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#51]
In the config file, if you remove the `stations` for a given section, then errors occur since `stations=None`. Is this by design or if it's `None` then use all available stations?

**Comment by micahjohnson150** [comment]
I thought this was fixed but I will look into it. The goal was to have none use all the stations.

**Comment by micahjohnson150** [comment]
Not sure when this was fixed, but it was likely fixed with the onset of inicheck. I checked and it does currently work in our test. Closing.
