### ISSUE TITLE
Importing current git tag with python version 3

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/smrf#53]
With python 3, the current method for getting the current git tag using subrpocess.check_output returns a byte string. This can be fixed with another option in the command.

**Comment by scotthavens** [comment]
This appears to still be a problem. The commit string in the output files is not correct, both in the tag value or git hash

**Comment by jomey** [comment]
Another case for setuptools_scm?

**Comment by scotthavens** [comment]
That's what I was thinking.

The important thing though is we're getting the git hash if we're in a repo so we'd want to use the scheme that has the commit hash.

**Comment by scotthavens** [comment]
Fixed with #170
