### ISSUE TITLE
apply default behavior for inicheck

### ISSUE THREAD

**Issue by micah-prime** [USDA-ARS-NWRC/smrf#86]
https://github.com/USDA-ARS-NWRC/smrf/blob/dc3282391a4a37ff348db092e611c60f9c4fa9a3/smrf/framework/recipes.ini#L22

Does this syntax work? 

I could ```get check_colocation = default``` to work, but not ```apply_defaults = check_colocation```

**Comment by micahjohnson150** [comment]
The only examples I can find right now are showing apply defaults is meant for a whole section. And is set to true when that is desired.

e.g. 

[all_recipe]

trigger:         has_section = data
data:            apply_defaults = True

**Comment by scotthavens** [comment]
The config option for `check_colocation` was removed in #126. While this may have been a more general question, may be better issue for `inicheck`.
