### ISSUE TITLE
IPW in the Core Config

### ISSUE THREAD

**Issue by Hedrick-ARS** [USDA-ARS-NWRC/smrf#94]
IPW topos were deprecated as of SMRF 0.8.0, but as of SMRF 0.8.10 the CoreConfig still references them as possible options for the topo.

**Comment by micahjohnson150** [comment]
Oh really? Thanks for notifying us here! I will add it in on the next fix

**Comment by micahjohnson150** [comment]
You were obviously correct. Deprecated 0.8.0. I am removing it as part of the latest changes in the config.

**Comment by scotthavens** [comment]
There are no IPW references in the CoreConfig
