### ISSUE TITLE
Time zone capital or lowercase

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#96]
The `time_zone` value in the config file has to specifically be from the `pytz` list with correct captial case. For example, `mst` does not work but `MST` does. However, `utc` works when it should be `UTC` so somewhere SMRF is modifying the value. 

https://stackoverflow.com/questions/13866926/is-there-a-list-of-pytz-timezones

**Comment by jomey** [comment]
Alternatively you could use a little filter to match the input string against the available from `ptyz`

Example for 'mst' as given string, will return 'MST'

```python
import re

pattern = re.compile('^mst$', re.I)
next(filter(pattern.match, pytz.all_timezones))
```

**Comment by scotthavens** [comment]
Would this make users lazy in not looking up the actual timezone name? Just passing the string through is working now with minimal changes. The gotcha is that `pytz` has both a `utc` and `UTC` which is why it's worked so far. However, if the tests are changed to `UTC` all the gold files will have to be changed as well just for the time zone attribute...

**Comment by jomey** [comment]
I am mainly suggesting a case-insensitive lookup of the user input. Has the additional advantage that it is checked against valid ones and can catch errors early

**Comment by scotthavens** [comment]
Fully understand. We need to figure out what is better, case insensitive or not?

**Comment by jomey** [comment]
You make a good point regards enforcing/educating users to lookup proper timezone names.
The doc can always refer to the accepted list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by jomey** [comment]
For down the road: USDA-ARS-NWRC/inicheck/issues/53
