### ISSUE TITLE
Remove Basin Lat Long in favor of on the fly calculation

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/smrf#97]
We would like to remove the basin lat and long from the config file in exchange for calculating it on the fly from the topo.nc

**Comment by micahjohnson150** [comment]
@scotthavens how do you feel about this being abstracted and added to spatialnc? 
It feels to me like it might be used in other places besides smrf, at the very least it might be used by you guys for papers and analysis.

**Comment by scotthavens** [comment]
Where else does this get used? I don't see this being used many other places at a the moment. I can see #100 being moved to spatialnc since katana and others would use it.

**Comment by micahjohnson150** [comment]
The function I wrote to calculate the center is what I was thinking might go into spatialnc. You are right I don't think it gets used anywhere but I thought if might be useful for general analysis stuff. 

Thats a good call on #100, I will try to add that to spatialnc.

**Comment by scotthavens** [comment]
The basin lat/lon is only used in the solar angle calucation that was improved on it PR #141. Down the road, we can calculate the sun angle for every point on the basin which would allow us to remove this.
