### ISSUE TITLE
Several config items to alterred in favor of verbosity

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/smrf#98]
This is still a work in progress but there a dozen or so item names in the config file should be renamed to be more verbose about their nature. This was per multiple meetings between @scotthavens , @Hedrick-ARS , @etrujil , @robertson-mark , and @micahjohnson150  during August 2019.

TLDR; Highlights

* Most values associated to a model were renamed with a model name proceeding it
* There have been a couple items kicking around in thermal, solar, and albedo that are not actually being used. They are being deleted.
* New section was formed for cloud factor, all solar distribution related items are moved to cloud factor
* Stations section will be deleted and those items are being moved to MYSQL and CSV sections

Listed below for smrf as of 08-22-2019

**TOPO**
* threading --> topo_threading

**STATIONS --> DELETED** 

**GRIDDED**
* file  --> wrf_file
* directory --> hrrr_directory
* n_forecast_hours --> DELETED
* zone_number --> MOVED TO  topo > zone_number
* zone_letter --> MOVED TO  topo > zone_letter

**ANY**
* mask --> grid_mask
* power --> idw_power
* slope --> detrend_slope
* dk_nthreads --> dkncores
* method --> grid_method
* variogram --> grid_variogram
* nlags --> grid_nlags
* anisotropic_scaling --> grid_anisotropic_scaling
* anisotropic_angle --> grid_anisotropic_angle
* coordinates_type --> grid_coordinates_type
* regression_method --> DELETED

**VAPOR PRESSURE**
* nthreads --> dew_point_nthreads
* tolerance --> dew_point_tolerance
* min = 10.0 --> min = 20.0

**WIND**
* peak --> station_peak
* reduction_factor: default = 0.7 --> reduction_factor:default = 1.0
* wind_ninja_tz:default =Europe/London --> wind_ninja_tz:default =UTC
* wind_ninja_dxdy:default =None --> wind_ninja_dxdy:default =100

**PRECIP**
* nasde_model --> new_snow_density_model
* nasde_model:default = marks2017 --> new_snow_density_model:default = susong1999
* time_steps_to_end_storm --> marks2017_hours_to_end_storms *This comes with other work which will occur in another issue*
* adjust_undercatch --> station_adjust_for_undercatch
* catchment_model_default --> station_undercatch_model_default
* distribute_drifts  morphed into precip_rescaling_model. *Another issue will be assigned*
* All parameters associated to the winstral precip rescaling are being renames winstral_*

**ALBEDO**
* grid_method ---> DELETED
* power --> DELETED
* start_decay --> date_method_start_decay
* end_decay --> date_method_end_decay
* decay_power --> date_method_decay_power
* veg_default --> date_method_veg_default
* veg_41 --> date_method_veg_41
* veg_42 --> date_method_veg_42
* veg_43 --> date_method_veg_43
* litter_albedo --> hardy2000_litter_albedo
* litter_default --> hardy2000_litter_default
* litter_veg_41 --> hardy2000_litter_veg_41
* litter_veg_42 --> hardy2000_litter_veg_42
* litter_veg_43 --> hardy2000_litter_veg_43 

** NEW SECTION --> cloud_factor**

**SOLAR**
* distribution --> moved to cloud_factor
* detrend --> moved to cloud_factor
* slope --> moved to cloud_factor
* stations --> moved to cloud_factor
* max --> moved to cloud_factor
* min --> moved to cloud_factor
* mask --> moved to cloud_factor
* grid_method --> moved to cloud_factor
* dk_nthreads --> moved to cloud_factor
* regression_method --> moved to cloud_factor
* grid_local --> moved to cloud_factor
* grid_local_N --> moved to cloud_factor
* variogram_model --> moved to cloud_factor        
* nlags --> moved to cloud_factor                     
* krig_weight --> moved to cloud_factor                
* anisotropy_scaling --> moved to cloud_factor           
* anisotropy_angle --> moved to cloud_factor
* coordinates_type --> moved to cloud_factor             

**THERMAL**
* method --> clear_sky_method
* nthreads --> marks1979_nthreads

**SOIL_TEMP**
* NONE

**OUTPUT**
* NONE

**LOGGING**
* Logging --> system

**SYSTEM**
*max_values --> queue_max_values

**Comment by micahjohnson150** [comment]
@scotthavens  Hey it looks like storms.time_since_storms in distribute for susong1999 uses the time_to_end_storms which we originally decided to rename marks2017_----- I am assuming we don't want to stick with that convention. Do we want to not change it?

**Comment by scotthavens** [comment]
Lets keep with the pattern of verbosity `susong1999_time_to_end_storms`
